version: '3'
services: 
  expa2podio:
    image: k2589/armosw:0.2
    ports: 
      - "5051:5000"
    environment: 
      - LOGGING_LEVEL=DEBUG
      - LOGGING_CONSOLE=true
    volumes: 
      - ./src:/app
    restart: always
 
